language: php

branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true

env:
#  - MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql
#  - MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql
#  - MAGENTO_VERSION="magento-ce-1.6.2.0" DB=mysql
#  - MAGENTO_VERSION="magento-ce-1.7.0.2" DB=mysql
  - MAGENTO_VERSION="magento-ce-1.8.0.0" DB=mysql
#  - MAGENTO_VERSION="magento-ce-1.8.1.0" DB=mysql

php:
#  - 5.3
  - 5.4
#  - 5.5

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS `magento_travis`; CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --no-interaction --working-dir ./tests/
  - curl https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar -o bin/n98-magerun && chmod +x $_
  - export TEST_MAGENTO_ROOT="./tests/${MAGENTO_VERSION}"
  - bin/n98-magerun install --magentoVersionByName="${MAGENTO_VERSION}" --installationFolder="./tests/${MAGENTO_VERSION}" --dbHost=localhost --dbUser=root --dbPass='' --dbName="magento_travis" --installSampleData=yes --useDefaultConfigParams=yes --baseUrl="http://travis.magento.local/"

script:
  - bin/phpunit
  - php tests/check-coverage.php clover.xml 65

